<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number is Registered in Whatsap_34aab5</name>
   <tag></tag>
   <elementGuidId>20c20e55-b3e1-4579-a002-8acb0f31d664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isWhatsapp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isWhatsapp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68792e47-9428-4bf7-9429-eea2e49266ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f2637588-e2a6-428f-8ddf-c0588de242c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isWhatsapp</value>
      <webElementGuid>ad28a64b-f0f7-4dae-a5d7-61928ffa9ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isWhatsapp</value>
      <webElementGuid>c94d368f-76cb-499a-af87-e92032a91115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Is Phone Number Registered in Whatsapp</value>
      <webElementGuid>4acb1025-bc7d-4ce7-a023-deb03b4687d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d84cbbdb-d08b-41d1-be48-e2a086fe0d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isWhatsapp&quot;)</value>
      <webElementGuid>87f2731f-1abc-41a6-b476-c9087c865ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isWhatsapp']</value>
      <webElementGuid>3d35d1f9-7a2c-434b-b186-294f1e31055a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset[2]/div[5]/div/input</value>
      <webElementGuid>f0f5ba22-baaf-4534-be31-80683c37cb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>8e1fafdc-fbec-4358-b6ea-15409e6ef1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'isWhatsapp' and @id = 'isWhatsapp' and @title = 'Is Phone Number Registered in Whatsapp']</value>
      <webElementGuid>9ec933de-9dfc-4778-b56c-3cfb13c17e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
