<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_is_subscribed</name>
   <tag></tag>
   <elementGuidId>a1e46fa3-a463-4ae3-a89b-4124733559b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_subscribed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_subscribed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2b3deff-f921-40db-b5f6-078a4d309d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>36c45fa1-a200-4685-85b0-cf5d7218f91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_subscribed</value>
      <webElementGuid>d70c33e0-7597-43b2-9a38-1e7b9ebb488e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up for Newsletter</value>
      <webElementGuid>ae4aafb1-e707-4062-8eff-c191ee07f5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>233f60d5-43f3-4dbd-8590-fac51658f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_subscribed</value>
      <webElementGuid>f415e898-2e05-4414-aa91-e37c0edc4fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5f19cd20-5161-4b0d-8954-44fee377148e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_subscribed&quot;)</value>
      <webElementGuid>5067164c-0742-4194-8629-b90b771cc0de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_subscribed']</value>
      <webElementGuid>6217d1ae-cf37-4416-81de-10cb90a18b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[3]/input</value>
      <webElementGuid>2f0d7b0f-6757-48e5-be14-b2ca5fb960af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6cb0b306-4f3b-4a90-80fc-4118ac8c7193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_subscribed' and @title = 'Sign Up for Newsletter' and @id = 'is_subscribed']</value>
      <webElementGuid>03d11fd5-3863-4178-88a1-e51207b4d9f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
