<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for registering with ICUBE SW_2b2bc5</name>
   <tag></tag>
   <elementGuidId>ae08ec04-f068-4af2-ad42-2cb3f4ffa9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.message-success.success.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>942f6bc0-717e-4607-9524-d35b9b7fec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { class: 'message-' + message.type + ' ' + message.type + ' message', 'data-ui-id': 'message-' + message.type }</value>
      <webElementGuid>b79643e1-24f8-4f73-83b7-7e8b2d4d4468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message-success success message</value>
      <webElementGuid>9950d29d-e0fb-4fd2-97d3-ac4f22cfde1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-id</name>
      <type>Main</type>
      <value>message-success</value>
      <webElementGuid>84fc939c-8e3d-48ac-b8d1-6d839a89e102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for registering with ICUBE SWIFT demo store .</value>
      <webElementGuid>b2289898-e29a-4f26-9ef2-2faaf6840192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;page messages&quot;]/div[2]/div[@class=&quot;messages&quot;]/div[@class=&quot;message-success success message&quot;]</value>
      <webElementGuid>fe86604a-12a3-4438-9742-7b9af1824f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div/div[2]/div/div</value>
      <webElementGuid>7ba43c0a-ebd4-40c4-bf1e-593e4604e939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR - Indonesian Rupiah'])[2]/following::div[5]</value>
      <webElementGuid>fc58b5dc-46f1-47f7-b0ca-be8f9b4c0fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[4]/preceding::div[2]</value>
      <webElementGuid>db5c3641-21ab-4999-a72a-e2f43b2e20ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]/div/div</value>
      <webElementGuid>cbdbdbbc-2921-4652-a260-ff2b0ca4d148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thank you for registering with ICUBE SWIFT demo store .' or . = 'Thank you for registering with ICUBE SWIFT demo store .')]</value>
      <webElementGuid>4f52e62f-0b10-4692-ae39-f638b13f58c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
