<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Account</name>
   <tag></tag>
   <elementGuidId>94972acd-0f8c-4cc0-a4a9-d1749364f38c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idZAwh5DED</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'My Account')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90311519-62f1-45c3-93c6-bb998f192656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://b2cdemo.getswift.asia/customer/account/</value>
      <webElementGuid>5cd687ff-ca3b-46bb-aa22-b6fa3ff41ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idZAwh5DED</value>
      <webElementGuid>8ca7b3bc-b656-4b7f-b522-fae59be68018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>ab89537d-e833-4752-ad28-50c26729dac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idZAwh5DED&quot;)</value>
      <webElementGuid>7c0754c3-ab1c-47a2-b372-09954181a78f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='idZAwh5DED']</value>
      <webElementGuid>93a5fdd6-731c-4572-a341-36a51dfac1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='html-body']/div[2]/div/div/header/div[3]/div/ul/li[2]/div/ul/li/a</value>
      <webElementGuid>d853c8cb-c272-4c66-b812-d43230aab14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Account')]</value>
      <webElementGuid>1fc355bf-8686-4ea4-b68d-ed79ed5d1bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/following::a[1]</value>
      <webElementGuid>f5ff91d0-d5ec-46a9-99af-877b4c3eacbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, Ridho Tiyar!'])[1]/following::a[1]</value>
      <webElementGuid>2d69e0bb-bc04-435d-a5c5-b944f678a02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wish List'])[1]/preceding::a[1]</value>
      <webElementGuid>02fe4ea1-d69f-40cb-92b8-07572fef7a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::a[2]</value>
      <webElementGuid>fe0afcb2-8bf2-4c7f-a3a9-c579a2d744d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Account']/parent::*</value>
      <webElementGuid>6da1a225-3094-4e71-a47e-fc1a6291af79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://b2cdemo.getswift.asia/customer/account/')]</value>
      <webElementGuid>252fd49f-8f4a-4b9a-bbd5-f6b6d415ec62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/a</value>
      <webElementGuid>d1063816-a4db-47f2-bd77-2d052cdb279b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://b2cdemo.getswift.asia/customer/account/' and @id = 'idZAwh5DED' and (text() = 'My Account' or . = 'My Account')]</value>
      <webElementGuid>4a50f418-e8e6-44cc-9bae-806a91f081c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
